# Calcul numérique TP1

## Partie 1 : Les bases en Python

Ce TP a pour objectif de vous familiariser avec les commandes de base en Python, mais également de vous faire découvrir les outils de calcul matriciel (avec `numpy`) que nous allons utiliser sur l'ensemble des TPs de calcul numérique.

Vous pouvez utiliser ce notebook directement pour y mettre vos éléments de code, vos commentaires et notes concernant l'ensemble de la séance.

### Exercice 1: les types et les conteneurs

1) Vérifier les types des valeurs suivantes en exécutant la commande `type(4)`. Si certains de ces types sont encore inconnus, relire le cours sur les bases en python !

`4; 4.0; -1; 2.4; None; a; ’hello’; "hello"; 0; True; False
[1, 2]; [1, 2.4]; [’a’, ’b’]; (1,3,5); ("a", 2); {’one’:’un’, ’zero’:’zéro’}`

In [5]:
a = 4
print(f"type de {a} : {type(a)}")

a = 4.0
print(f"type de {a} : {type(a)}")

a = -1
print(f"type de {a} : {type(a)}")

a = 2.4
print(f"type de {a} : {type(a)}")

a = None
print(f"type de {a} : {type(a)}")

a = 'a'
print(f"type de {a} : {type(a)}")

a = 'hello'
print(f"type de {a} : {type(a)}")

a = "hello"
print(f"type de {a} : {type(a)}")

a = 0
print(f"type de {a} : {type(a)}")

a = True
print(f"type de {a} : {type(a)}")


a = False
print(f"type de {a} : {type(a)}")


a = [1,2]
print(f"type de {a} : {type(a)}")


a = [1, 2.4]
print(f"type de {a} : {type(a)}")


a = ['a', 'b']
print(f"type de {a} : {type(a)}")


a = (1,3,5)
print(f"type de {a} : {type(a)}")


a = ("a", 2)
print(f"type de {a} : {type(a)}")


a = {'one':'un', 'zero':'zéro'}
print(f"type de {a} : {type(a)}")



type de 4 : <class 'int'>
type de 4.0 : <class 'float'>
type de -1 : <class 'int'>
type de 2.4 : <class 'float'>
type de None : <class 'NoneType'>
type de a : <class 'str'>
type de hello : <class 'str'>
type de hello : <class 'str'>
type de 0 : <class 'int'>
type de True : <class 'bool'>
type de False : <class 'bool'>
type de [1, 2] : <class 'list'>
type de [1, 2.4] : <class 'list'>
type de ['a', 'b'] : <class 'list'>
type de (1, 3, 5) : <class 'tuple'>
type de ('a', 2) : <class 'tuple'>
type de {'one': 'un', 'zero': 'zéro'} : <class 'dict'>


2) Affecter les variables suivantes: `var_int = 1; var_float = 2.51; var_str = ’hello’; var_bool = True` 

Convertir les types de ces quatre variables en utilisant les fonctions `int(); float(); str(); bool()`. 

Vérifier les valeurs et les types obtenus après conversion.
En particulier remarquer le résultat de `bool(var_int)` et `int(var_float)`.
Vous pouvez bien sûr tester d’autres combinaisons, par curiosité.

In [24]:
var_int = 1; var_float = 2.51; var_str = "hello"; var_bool = True
print(bool(var_int))
print("type : ", type(bool(var_int)))

print(float(var_int))
print("type : ", type(float(var_int)))
print(str(var_int))
print("type : ", type(str(var_int)))

print(int(var_float))
print("type : ", type(int(var_float)))
print(str(var_float))
print("type : ", type(str(var_float)))
print(bool(var_float))
print("type : ", type(bool(var_float)))

print(bool(var_str))
print("type : ", type(bool(var_str)))

print(int(var_bool))
print("type : ", type(int(var_bool)))
print(float(var_bool))
print("type : ", type(float(var_bool)))
print(str(var_bool))
print("type : ", type(str(var_bool)))


True
type :  <class 'bool'>
1.0
type :  <class 'float'>
1
type :  <class 'str'>
2
type :  <class 'int'>
2.51
type :  <class 'str'>
True
type :  <class 'bool'>
True
type :  <class 'bool'>
1
type :  <class 'int'>
1.0
type :  <class 'float'>
True
type :  <class 'str'>


3) Pour les variables `var` suivantes, donner les valeurs qu’elles contiennent (on pourra utiliser la commande `print(var)`) et  leur type. Faites d’autres propositions permettant d’obtenir le même contenu.

Que retourne `var[2]` ? Quel effet a la commande `var[2] = 6`, pourquoi ? Si il y a une erreur, proposer une commande adaptée qui ne génère pas d’erreur.

In [50]:
var = list(range(10))
print(f"valeur : {var} - type : {type(var)}")
var = [0,1,2,3,4,5,6,7,8,9]
print(f"valeur : {var} - type : {type(var)}")



var = "informatique"
print(f"valeur : {var} - type : {type(var)}")
var = 'Informatique'
print(f"valeur : {var} - type : {type(var)}")

var = {"info":3, "maths":5, "musique":10, "foot":7}
print(f"valeur : {var} - type : {type(var)}")
var = {}
var["info"] = 3
var["maths"] = 5
var["musique"] = 10
var["foot"] = 7
var[2] = 6
print(var[2])
print(f"valeur : {var} - type : {type(var)}")

print(var[list(var)[2]])


valeur : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] - type : <class 'list'>
valeur : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] - type : <class 'list'>
valeur : informatique - type : <class 'str'>
valeur : Informatique - type : <class 'str'>
valeur : {'info': 3, 'maths': 5, 'musique': 10, 'foot': 7} - type : <class 'dict'>
6
valeur : {'info': 3, 'maths': 5, 'musique': 10, 'foot': 7, 2: 6} - type : <class 'dict'>
10


### Exercice 2: les entrées / sorties

1) Avec la fonction `input()`créer une variable `var`contenant une valeur qui aura été saisie à la main au clavier. Afficher cette variable avec la fonction `print`. Cette approche sera surtout utile lorsque vous utiliserez un script.

In [36]:
var = input()
print("Entrée clavier : ", var)


bonjour à tous
Entrée clavier :  bonjour à tous


2) Créer un fichier (avec `vim` par exemple) contenant le texte suivant:

`MAN: Mise à niveau
INFO: Master d'informatique`

- [ ] ouvrir ce fichier avec la commande ci-dessous et les arguments appropriés. Afficher les lignes les unes après les autres.
- [ ] écrire ensuite une troisième ligne dans le fichier précédent avec la fonction `write()` contenant:

`M1: première année de master`

Attention de pas oublier de **refermer** le fichier après l'avoir ouvert.

In [38]:
f = open('le_fichier', 'a', encoding = 'utf8')
f.write("M1: première année de master")
f.close()

### Exercice 3: écrire des fonctions en Python

Vous avez à disposition un dictionnaire de prononciations phonétiques. Une prononciation est une séquence de symboles phonétiques séparés par des espaces. Pour chaque ligne, vous disposez d’un mot, de sa prononci- ation phonétique donnée selon l’alphabet X-Sampa et de sa prononciation phonétique donnée selon l’alphabet IPA. Vous ne considérerez que la prononciation donnée en X-Sampa. Les mots et les prononciations sont séparées par des point-virgules.

**Préliminaire**
Le code ci-dessous vous permet d'afficher une chaine de caractère. Vérifier que la chaine de caractère s'affiche correctement.

In [ ]:
ma_chaine = 'Hello World'
print(ma_chaine)

1) Ouvrir le fichier de prononciation `synpaflex-pronunciation-dictionary.txt` et afficher les $n$ premières lignes du fichier (équivalent de la commande unix `head`).
Pourquoi y a-t-il une ligne vide entre chaque affichage ? Corriger cela avec la fonction `strip()`.

In [ ]:
f = open('synpaflex-pronunciation-dictionary.txt', 'r')

f.close()

2) Créer une fonction `ReadPron(name)` prenant en argument le nom du fichier de pronciation. Cette fonction lit l'ensemble du fichier de prononciation, stocke les lignes une à une dans un dictionnaire et retourne ce dictionnaire. Les clés seront les mots. Les valeurs seront des prononciations suivant l’alphabet X-SAMPA. Penser à supprimer les espaces en début et fin de chaîne de caractère.

In [ ]:
def ReadPron(name):
    f = open(name, 'r')
    dicPron = {}
    ...
    return dicPron

DicPron = ReadPron('synpaflex-pronunciation-dictionary.txt')


3) Créer une fonction `AfficherPron(m, dicPron)` qui prend en argument un mot et le dictionnaire fourni par la fonction précédente et affiche à l'écran la prononciation correspondante à ce mot. 

Attention au cas où le mot ne serait pas dans le dictionnaire.

- [ ] donner la pronciation du mot _abandonna_

In [ ]:
def AfficherPron(m, dicPron):
    ...
    
DicPron = AfficherPron('abandonna', DicPron)

4) Créer une fonction `AfficherMots(p, dicPron)` qui stocke dans une liste l'ensemble des mots qui ont une prononciation donnée, les compte et les affiche.

- [ ] donner l'ensemble des mots qui se prononcent "/k u l e/". **Attention** il faut respecter la syntaxe du fichier de prononciation.

In [ ]:
def AfficherMots(p, dicPron):
    mots = []
    ...
    return mots

motsLi = AfficherMots(' k u l e', DicPron)

---
## Partie 2: Utilisation de Numpy pour le calcul vectoriel

Numpy est un module Python pour le calcul numérique. Il est écrit en C. On l'utilise principalement pour le calcul matriciel, le traitement de données multi-dimensionnelles. C'est un outil de base pour le **machine learning**.

Une matrice est une structure de données en forme tableau à 2 dimensions disposée en colonnes et en lignes. La matrice ci dessous est composée de 4 colonnes et 3 lignes:
$$\begin{bmatrix}
2 & -5& -11 & 0 \\ -10 & 4 & 6 & 13 \\ 4 & 7 & 12 & -2
\end{bmatrix}$$

In [51]:
import numpy as np
np.array([[2, -5, -11, 0], 
    [-10, 4, 6, 13],
    [4, 7, 12, -2]])

array([[  2,  -5, -11,   0],
       [-10,   4,   6,  13],
       [  4,   7,  12,  -2]])

### Exercice 1: Prise en main

1) Cette librairie permet de faire des opérations rapides sur les vecteurs et les matrices qu'on appelle des `array`. Tous les éléments d'un tableau (ou array) sont du même type. 
- [ ] Afficher les types des variables suivantes.
- [ ] Comment fonctionne le typage des éléments d'un array ?

In [52]:
lst = [2, 3, 4, 1]
print('le type d une liste python est: ', type(lst))
a = np.array(lst)
print('le type d un array est: ', type(a))
print('le type des éléments de lst est: ', type(a[0]))
b = np.array([2.0, 3, 4, 1])
print('le type des éléments de lst est: ', type(b[2]))
c = np.array(lst, dtype = complex)
print('On peut modifier le type des éléments d un array: ', type(c[0]))

le type d une liste python est:  <class 'list'>
le type d un array est:  <class 'numpy.ndarray'>
le type des éléments de lst est:  <class 'numpy.int64'>
le type des éléments de lst est:  <class 'numpy.float64'>
On peut modifier le type des éléments d un array:  <class 'numpy.complex128'>


2) Un **vecteur** est un array de dimension 1. Une **matrice** est un array de dimension 2. On peut vérifier la dimension avec l'attribut `shape`. 
- [ ] Afficher les dimensions des arrays A et B suivantes.
- [ ] Afficher le type des éléments de B.
- [ ] Modifier le type de B pour que tous ses éléments soient des entiers.
- [ ] Modifier la matrice pour que tous ses éléments soient des booléens.
- [ ] Peut-on faire cette dernière opération sur la matrice B ? Pourquoi

In [71]:
A = np.array([1,2,3,4])
print("Dim A : ", A.shape)


B = np.array([[1,2,3,4],[5,6,7,8]])

print("Dim B : ", B.shape)
print(B.dtype)
B = np.array(B, dtype=np.float16)
print(B.dtype)


B = np.array(B, dtype=bool)
print(B)

Dim A :  (4,)
Dim B :  (2, 4)
int64
float16
[[ True  True  True  True]
 [ True  True  True  True]]


L'une des puissances de numpy est de pouvoir faire des opérations rapidement en utilisant les indices de chacun de ses éléments (slicing).
- [ ] Indiquer pour chacun des `print` un commentaire expliquant ce qui est affiché.
- [ ] Observer l'exemple ci-dessous et afficher le dernier élément de la première ligne de la matrice C.
- [ ] Quel est le type de la variable `column` ?

In [78]:
C = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])


print("C =", C) #Affichage de la matrice
print("C[1] =", C[1]) #Affichage du deuxième vecteur de la matrice
print("C[1][2] =", C[1][2]) #Affichage du 3eme scalaire du 2eme vecteur de la matrice
print("C[1,2] =", C[1,2]) # //
print("Dernier élément de la 1ère ligne =", C[0,-1])
print("Deux premiers éléments de la 2eme ligne =", C[1,:2])

column = [];
print("Type de column : ", type(column))
for row in C:
  column.append(row[2])   

print("3eme colonne =", column)

C = [[ 1  4  5 12]
 [-5  8  9  0]
 [-6  7 11 19]]
C[1] = [-5  8  9  0]
C[1][2] = 9
C[1,2] = 9
Dernier élément de la 1ère ligne = 12
Deux premiers éléments de la 2eme ligne = [-5  8]
Type de column :  <class 'list'>
3eme colonne = [5, 9, 11]


- [ ] Construire un tableau `letters` où chaque élément est un mot de la phrase. Les mots sont séparés par des espaces.
- [ ] Commenter les lignes d'affichage pour expliquer l'opération de slicing qui est réalisée.

In [82]:
sentence = 'le chateau dans le ciel est film japonais'
letters = np.array(sentence.split(" "))
print(letters)
print(letters[2:5]) #Affichage du 3eme mots au 6eme exclu
print(letters[2:8:2]) #Affichage à partir du 3eme mot jusqu'au 9eme exclu avec un pas de 2
print(letters[:-5]) #Affichage du debut jusqu'au 6eme mot en partant de la fin exclu
print(letters[5:]) #Affichage du 6eme mot jusqu'à la fin
print(letters[:]) #Affichage du début à la fin
print(letters[::-1]) #Affichage du debut à la fin avec un pas de -1

['le' 'chateau' 'dans' 'le' 'ciel' 'est' 'film' 'japonais']
['dans' 'le' 'ciel']
['dans' 'ciel' 'film']
['le' 'chateau' 'dans']
['est' 'film' 'japonais']
['le' 'chateau' 'dans' 'le' 'ciel' 'est' 'film' 'japonais']
['japonais' 'film' 'est' 'ciel' 'le' 'dans' 'chateau' 'le']


A partir de la matrice X donnée ci-dessous:
- [ ] Récupérer les 2 premières lignes et les 3 premières colonnes
- [ ] Récupérer la première ligne, toutes les colonnes
- [ ] Toutes les lignes, la 2ème colonne
- [ ] Toutes les lignes, la 1ère et 3ème colonnes.

In [102]:
X = np.array([[2, -5, -11, 0], 
    [-10, 4, 6, 13],
    [4, 7, 12, -2]])

print(X[:2], '\n')
print(X[:,:3], '\n')

print(X[0], '\n')

print(X[:,1], '\n')

print(X[:,::2], '\n')




[[  2  -5 -11   0]
 [-10   4   6  13]] 

[[  2  -5 -11]
 [-10   4   6]
 [  4   7  12]] 

[  2  -5 -11   0] 

[-5  4  7] 

[[  2 -11]
 [-10   6]
 [  4  12]] 



3) A l'aide des arrays particuliers `np.eye()`, `np.zeros()` et `np.ones()`, construire:
- [ ] un vecteur contenant 5 zéros
- [ ] un vecteur contenant 4 1
- [ ] une matrice ayant 2 lignes et 5 colonnes ne contenant que des zéros
- [ ] une matrice carrée de dimension 3 ne contenant que des 1
- [ ] une matrice identité de dimension 3.
Vous vous aiderez de la documentation en ligne de numpy.

In [104]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


Il existe encore plein de matrices spéciales avec Numpy. En voici quelques unes qui nous serviront pendant les TPs. Observez bien comment les utiliser.

In [ ]:
x = np.arange(9)       #liste de n éléments de 0 à n-1
y = np.linspace(0,1,5) #np.linspace(debut, fin, nb)

4) Nous allons maintenant étudier les attributs et méthodes de ces arrays. 
- [ ] Expliquer avec un commentaire sur chaque ligne, à quoi correspondent chacun des attributs ou méthodes suivantes. 
- [ ] En particulier bien observer le comportement de `w.sort()` sur la matrice w.

In [ ]:
x = np.arange(9)
print(x.size, x.shape, x.ndim)
y = x.reshape((3,3))
print(y.size, y.shape, y.ndim)

print('type: ', y.dtype)
print('min: ', y.min())
print('max: ', y.max())
print('argmax: ', y.argmax())
print('sum: ', y.sum())
print('sum0: ', y.sum(axis=0))
print('sum1: ', y.sum(axis=1))

w = np.eye(3)
w.sort()

5) Masking. On définit un masque m qui contient des booléens. L'utilisation du masking permet de ne récupérer que les éléments de b qui sont à `True` dans le masque. 
- [ ] Faites l'opération qui consiste à ne récupérer que les éléments qui sont à `True`

In [ ]:
b = np.array([[ 2, 4, 6, 8], [12, 14, 16, 18], [22, 24, 26, 28]])
m = np.array([[True, False, True, False],[True, False, True, False],[True, False, True, False]])

6) Opérations matricielles. Nous allons maintenant faire des opérations entre les différents arrays. On définira une matrice m de dimensions $N \times M$ telle que ses éléments sont $m_{ij}$ avec $i \in [0; M]$ l'indice de la ligne et $j \in [0; M]$ l'indice de la colonne.

Créer deux matrices A et B non carrées de dimension au moins 3 et calculer les matrices suivantes:
- [ ] `A+B` la somme matricielle $A+B$ (équivalent à la somme terme à terme)
- [ ] `A*B` le produit d'Hadamard (ou produit terme à terme **différent du produit matriciel**) $D = A \cdot B$ tel que $d_{ij} = a_{ij} \times b_{ij}$
- [ ] `A.dot(B)` le produit matriciel $E = A \times B$
- [ ] `A.transpose()` ou `A.T` la transposition d'une matrice $F = ^tA$
- [ ] `A < B` le masque correspondant aux indices tels que $a_{ij} < b_{ij}$
- [ ] les valeurs terme à terme issues de l'opération $\sin(A) \cdot e^{- A^2 /2}$

7) Concaténation de matrices. Les matrices peuvent être accolées soit verticalement (`np.vstack()`) soit horizontalement (`np.hstack()`). Toujours bien vérifier la dimension sur laquelle on fait la concaténation pour ne pas tromper entre les lignes et les colonnes.
- [ ] concaténer les matrices a et b en vérifiant que l'axe choisi est adapté.
- [ ] utiliser la transposition de matrice `np.transpose()` pour faire la concaténation suivant un autre axe.

In [ ]:
a = np.ones((3,4))
b = np.array([[ 2, 4, 6], [12, 14, 16], [22, 24, 26]])

#print(np.concatenate((a,b), axis=0))
#print(np.hstack((a,b)))

#print(np.concatenate((a,b), axis=1))
#print(np.hstack((a,b)))

### Exercice 2: Calcul matriciel pour l'algèbre linéaire

Maintenant que nous avons vu les bases des opérations sur les matrices en numpy, nous allons pouvoir effectuer des opérations vues en cours d'algèbre linéaire.

1) Inverse d'une matrice. On n'oubliera pas de vérifier si une matrice est inversible en calculant son déterminant: $\text{A est inversible} \Leftrightarrow \det(A) \neq 0$

Le calcul du déterminant peut être fait à la main, et vérifié avec la fonction `linalg.det(A)`.
- [ ] créer une fonction qui prend une matrice en argument et vérifie si elle est inversible.
- [ ] déterminer les matrices inverses de a et b. 
- [ ] vérifier que l'opération donne un résultat correct. On rappelle que $A^{-1} \times A = I$, $I$ étant la matrice identité et $A^{-1}$ la matrice inverse.

In [ ]:
import numpy.linalg as la
    
a = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

b = np.array([[4, 7],
              [2, 8]])
a[0,0]

### Exercice 3: subtilités en Python

Etant donné que les variables ne sont ni typées, ni affectées de manière aussi forte qu'en C, on doit faire attention à quelques éléments quand on programme en Python.

- [ ] Que remarquez-vous sur les valeurs de la matrice p, une fois le code ci-dessous exécuté? Expliquer.
- [ ] Proposer une solution pour que la matrice p ne soit pas modifiée.

In [ ]:
p = np.array([[ 2, 4, 6, 8], [12, 14, 16, 18], [22, 24, 26, 28]])
s = p
print('s: ', s)
s[0,0] = 0
print('s: ', s)
print('p: ', p)

On peut définir en Python des fonctions qui prennent en entrée des tableaux numpy. Cependant il faut faire attention à ce que les entrées soient au bon format.
- [ ] Utiliser la fonction `np.vectorize()` pour vectoriser la fonction `f`.

In [ ]:
def f(x):
    k, s = 0.0,0
    while k < x:
        k +=1
        s += k
    return s

print('f(3) = ', f(3))
x = np.linspace(0,1,5)
print('f(x) = ', f(x))

---
## Partie 3: Faire des statistiques avec Numpy

Numpy contient les fonctions statistiques de base. Ces fonctions s'appliqueront sur des tableaux de type `array`. 

### Exercice 1: fonctions statistiques classiques

1) Pour la matrice a suivante, calculer:
- [ ] la variance globale sur tous les éléments et vérifier que l'écart-type au carré est bien égal à cette variance: $var(X) = \sigma(X)^2$
- [ ] la moyenne sur les colonnes.

In [ ]:
a = np.array([[ 2, 4, 6, 8], [12, 14, 16, 18], [22, 24, 26, 28]])
print('moyenne: ', a.mean()) #moyenne de tous les éléments
print('écart-type: ', a.std(axis = 0)) #écart-type p/r aux colonnes
print('médiane: ', np.median(a, axis = 1)) #median p/r aux lignes

### Exercice 2: Génération de nombres aléatoires suivant des lois de probabilités

On pourra également utiliser la librairie `numpy.random` pour la génération de nombres aléatoires.
- [ ] vérifier les dimensions de chacune des arrays générés.
- [ ] générer 1000 valeurs suivant une loi normale centrée réduite
- [ ] vérifier que la moyenne de ces 1000 valeurs est bien 0 et que l'écart-type est 1.

In [ ]:
import numpy.random as rdm

print(rdm.rand(3)) #génère des nombres suivant une loi uniforme sur [0,1]
print(rdm.rand(3))

#print(rdm.binomial(10,0.3, (2,5)))#génère des nombres suivant une loi binomiale avec n=10 et p=0.3
#print(rdm.normal(-3.5, 0.3, 10))#génère des nombres suivant une loi normale avec m=-3.5 et s=0.3
#print(rdm.poisson(4.3, 5))#génère des nombres suivant une loi de poisson avec lambda=5

In [ ]:
letters = np.array(['a', 'b', 'c', 'd'])
rdm.shuffle(letters)
print(letters)
print(rdm.choice(letters,2)) #tirage aléatoire de 2 élements de letters

### Exercice 3: Visualisation des distributions aléatoires

En utilisant la librairie `matplotlib` vous pourrez tracer des graphiques. Cela vous sera utile pour représenter par exemple des distributions de nombres générés aléatoirement.

- [ ] modifier les paramètres de loi (après avoir consulté la documentation correspondante) et observer les effets sur les distributions.

In [ ]:
import matplotlib.pyplot as plt
plt.hist(rdm.uniform(0,1,100))
plt.show()


In [ ]:
plt.hist(rdm.normal(4,2,100))
plt.show()

- [ ] par rapport à ce que vous connaissez des variables aléatoires. Quelle grandeur est observée sur le graphique ci-dessous ?

In [ ]:
L = np.sum(rdm.rand(40, 100000),0)
plt.hist(L, 25, normed=’True’)
plt.show()